name: form_builder_autocomplete
description: An advanced Autocomplete input extension widget for Flutter FormBuilder, supporting type-safe predictive text filtering and async data fetching.
version: 0.9.0
resolution: workspace
homepage: https://o7planning.github.io
repository: https://github.com/o7planning/form_builder_autocomplete

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_form_builder: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: